### ISSUE TITLE
Events Reporting

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#11]
We will have a new subject type called 'Event Reporting' (Individual) which will record details for the events.
This will be recorded in the subject registration form only

**Key Points**
- Registration location will be only village
- Additional text location fields : Hamlet, Ward / Municipality Area Name, Ward no, Colony name/no, 
- Reporting details
  - Name and designation of professional reporting [Text]
  - Place where event was organised [Text]
  - Reporting date [Date]
- Event details
  - Name of the event
  - Type of event
  - Date/Time of event - From [DateTime]
  - Date/Time of event - To [DateTime]
  - Hours [If single day event][Number]
  - Purpose of the event
  - Issue focussed
- Reach
  - Direct Reach - Boys
  - Direct Reach - Girls
  - Direct Reach - Men
  - Direct Reach - Women
  - Indirect Reach - Boys
  - Indirect Reach - Girls
  - Indirect Reach - Men
  - Indirect Reach - Women
- Key Highlights
  - Key Highlight [Image]
- Media coverage 
  - Type of Media coverage (Include None also as answer)
  - Name of media
- Key results / Outcome

**Comment by garimadosar5** [comment]
@nupoorkhandelwal 
Location setup is not correct- Village is not showing
