### ISSUE TITLE
[STCATP] Common Service Centre

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/stcatp#12]
Requirement document--

https://docs.google.com/spreadsheets/d/1uTDyTzJVAd0HfZXAltEnlvpsTre_QpXw/edit#gid=1127615964

- [x] Create a new Individual Subject Type & Registration form - Common Service Centre

- [x] Checklist - Common Service Centre - This will be a general encounter on this subject

- [x] CSC Monthly Reporting - This will be a general encounter with monthly scheduling

**Comment by garimadosar5** [comment]
**QA Notes-** 
 
**Registration -** 
- Partner is missing.
**Monthly reporting.**
Sum is wrong if 0 is filled. - Not fixed
![Screenshot_2021-08-09-14-37-09-57_e67de974eab1ae435bf1faa372eb4549.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f5d0b791-0429-4650-acf5-b287e6f7d21a)

**- Checklist -** 
Other details FEG -
Number of <Assest> question is not asking. - Not fixed.
