### ISSUE TITLE
[STCATP] Child Friendly Corners

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/stcatp#13]
Requirement document --

https://docs.google.com/spreadsheets/d/1xxaaLZNopcw15uElU0-zxEIQNTLSFngc/edit#gid=305957659

- [x] Create a new Individual Subject Type & Registration form - Child Friendly Corner

- [x] Checklist - Child Friendly Corner - This will be a general encounter on this subject

**Comment by garimadosar5** [comment]
QA Notes -
- Child friendly corner Registration form - 
Partner is missing. **Added this on second screen( under Reporting details)**
