### ISSUE TITLE
[STCATP] CPC GROUP TRAINING

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/stcatp#17]
Ref doc--
https://docs.google.com/spreadsheets/d/1jSTieCjWloqFeKpyTJR80QL7OdmpFDh3/edit#gid=1413142490

This will be general encounter -- CPC GROUP TRAINING

Fields-
1. Training details 
  Date of training (Start date - end date)
  Duration of training (in days) -Auto Calculated 
  Type of training - Coded
  Place of training 
  Name of the organisation who conducted training - Coded
  Type of resource person 
  Was exposure visit conducted?
  Topic of training
2. Trainee Details 
 Members (Subject type)
 Total no. of Outsider present (who is not a  group member)

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Place of training is not coded. **Why will it show coded? Are there any coded answers provided?** (It was given in requirement, now that is removed.)
- "CPC group members who attended training", not showing any subjects. **Fixed**
