### ISSUE TITLE
[STCATP] ADOLESCENT GROUP TRAINING

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/stcatp#18]
Ref doc- 
https://docs.google.com/spreadsheets/d/1jSTieCjWloqFeKpyTJR80QL7OdmpFDh3/edit#gid=1450869271

This will be general encounter on ADOLESCENT group-- ADOLESCENT GROUP TRAINING

Fields-
1. Training details
Date of training (Start date - end date)
Duration of training (in days) -Auto Calculated
Type of training - Coded
Place of training 
Name of the organisation who conducted training - Coded
Type of resource person
Was exposure visit conducted?
Topic of training
2. Trainee Details
Members (Subject type)
Total no. of Outsider present (who is not a group member)

**Comment by garimadosar5** [comment]
**QA Notes -** 
- End of training should be after start of training. **Fixed**
- Place of training is always Not known yet. **Fixed**
- Was exposure visit conducted? is missing. **Fixed**
- Not showing subjects in "Adolescent group members who attended training?" **Fixed**
