### ISSUE TITLE
[STCATP] SS Update Cancel Form & other SS related misc changes 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/stcatp#19]
- [x] Cancel From for SS Update Scheduled Visit
A new visit should be scheduled on the earliest visit date 

- [x] Stop showing particular Scheme once its Dropped out in the last update.

- [x] Also, no update visit should be scheduled until there is any scheme with status other than Dropped out.

**Comment by garimadosar5** [comment]
QA Notes - 
- Second point is not done. **The second point means that we need to stop showing scheme in the status update form once its dropped out and not in the summary!**
![Screenshot_2021-08-19-13-45-31-75_e67de974eab1ae435bf1faa372eb4549.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/48c37f0e-bc6e-4cc4-a1a7-9b1ecb803db0)
- When I am performing a visit, it is scheduling next visit on "one month from the encounter date" not on earliest date time. **Check now. Updated it but usually earliestVisitDateTime is used for scheduling visit during Cancel visits!**
