### ISSUE TITLE
Household Regsitration

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#2]
- [ ] Registration Form - https://docs.google.com/spreadsheets/d/1NKq9g6DE6IxMcKIbnTNMkFpSm5BZC3l6/edit#gid=466112620
- [ ] Add Member

Additional relations to be added mentioned in above sheet

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Social Group, Don't know option is missing.
- Did child also migrate? - Specify other is missing.
- Specify Other is missing in "Who is account holder".
