### ISSUE TITLE
[STCATP] STG TRAINING

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/stcatp#20]
Ref doc --
https://docs.google.com/spreadsheets/d/1jSTieCjWloqFeKpyTJR80QL7OdmpFDh3/edit#gid=1212443793

This will be general encounter on STG group-- STG GROUP TRAINING

**Comment by garimadosar5** [comment]
**QA Notes -** 
- End of training should be more than start of training.
- Place of training is not coded.
- FEG- Training member details.
FE - Adolescent group members who attended training, there is no value.
- Questions in the app are not matching with the questions given above. **Please refer the attached document.**
