### ISSUE TITLE
Report : Children Removed from Vulnerability

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#22]
https://docs.google.com/spreadsheets/d/1OgZwShkxeuOnChdD_HuHtBgs_eKx-dIV/edit#gid=445031720

Date Range will apply on exit date / when the child was removed from vulnerability.

**Comment by garimadosar5** [comment]
QA Notes - 
- Target is in numbers or in %. check once with Arjun or if this is the number then 60 in what time period.
- Date Range filter does not seem right. It is showing all the cases and when filetr is applied only exit cases are showing. Check once if that is how the filter should be.
- Reset button is not working to reset any filter. 
- Report is only showing three catagories of vulnerability.

**As discussed, updated the logic for total percentage in the requirement doc & report accordingly. please check**
