### ISSUE TITLE
[STCATP] [Report] Vulnerable children supported either to attend school and/or placed in skills training opportunities

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/stcatp#23]
Requirement doc-
https://docs.google.com/spreadsheets/d/1OgZwShkxeuOnChdD_HuHtBgs_eKx-dIV/edit#gid=445031720&range=A11

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Case Neha Sharma. She has exited from Out of school. but still showing in this report. This is wrong what if she has exited from Out of school last year and then again this year any vulnerability get identified then the case will start showing in this report. That will be wrong data. **Fixed**
