### ISSUE TITLE
[STCATP][Reports] Project MIS Report - ER3

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#24]
https://docs.google.com/spreadsheets/d/1AvBcssHonsota3UcYEWpOw2kILisAQaq/edit#gid=227783172

**Comment by nupoorkhandelwal** [comment]
Logic for most of the indicators is not clear.

**Comment by garimadosar5** [comment]
QA Notes - 
- Indicator - **"Number of training of Child protection workforce conducted"**. from which question it is taking the count for male/female etc. **From Other Stakeholders Training Attendees** **Fixed**
Case - Training Session. Here Child protection workforce is selected but not getting calculated in Count. **"There are no training attendees in the event registraion**
- When date range is applied. at some places where data is not there, showing 0 but some places it is blank.
- Indicator - **"Number of District Child Protection Unit personnel supported"**, where is this number coming from. Where user is putting achieved number. **User will put target and achieved both in the Monthly planner**
- For rest of the indicator, how it will count the numbers there is no question to capture male/female count. In those places it will be 'NA'
