### ISSUE TITLE
[STCATP][Report] Number of children or household member accessing social security scheme

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#25]
https://docs.google.com/spreadsheets/d/1OgZwShkxeuOnChdD_HuHtBgs_eKx-dIV/edit#gid=1096396508

This will give an idea of how many vulnerable children and their family member have accessed social security scheme.

**Comment by garimadosar5** [comment]
QA Notes - 
- If child is exited from a vulnerability program but still it is showing in the scheme report.
It is not mentioned anywhere in the requirement doc. Y**es, its not mentioned but a child will get counted irrespective it has exited or not the program.**
