### ISSUE TITLE
[STCATP] Important Stakeholder Details

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#26]
This is a form to record Stakeholder details

Subject Type : Important Stakeholder
Type : Individual

Key Fields
Stakeholder Name
Stakeholder Category
Designation
Contact Number
Email id

https://docs.google.com/spreadsheets/d/1AvBcssHonsota3UcYEWpOw2kILisAQaq/edit#gid=517621701

**Comment by garimadosar5** [comment]
QA Notes - 
- Can put some validation in email id field if required.
