### ISSUE TITLE
Additional Details for Household Family Member

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#3]
## Context
These details are captured only for family members of the vulnerable child. That's why this is kept separate from the Individual registration form. 

##  Following are the details
**Name of the Encounter / Form** : Family member additional details
**Fields**
Social Economic Details
- Educational Level
- Marital status
- Occupation
- Has any of the family member availed / availing social security schemes
- Do you have PAN card
- Do you have Aadhar card
Birth certificate details (Only asked for 0-18 years age)
- Questions in reference document

Reference Document : https://docs.google.com/spreadsheets/d/1NKq9g6DE6IxMcKIbnTNMkFpSm5BZC3l6/edit#gid=466112620

**Comment by garimadosar5** [comment]
QA Notes - 
- Question - "Has any of the family member availed / availing social security schemes"
Either make this question non-mandatory or add "NONE" as an option. -**Fixed**
- Migration questions are missing from the Reference document. **Check this --**https://docs.google.com/spreadsheets/d/1NKq9g6DE6IxMcKIbnTNMkFpSm5BZC3l6/edit#gid=466112620&range=A17:T17
- Post-registration status is missing. **Please check ..this question has been stroked out** https://docs.google.com/spreadsheets/d/1NKq9g6DE6IxMcKIbnTNMkFpSm5BZC3l6/edit#gid=466112620&range=V53:AC53
