### ISSUE TITLE
[STCATP][Report] MIS Report - ER1

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#30]
Ref doc --
https://docs.google.com/spreadsheets/d/1AvBcssHonsota3UcYEWpOw2kILisAQaq/edit#gid=227783172&range=A5

- [x] Aggregate Report

**Comment by garimadosar5** [comment]
**QA Notes -** 
- All the numbers are not clickable in the report. (achieved report) **Right now only aggregate report is done. We have not started on linelists**
- Indicator - **Number of Child Protection Committees (CPCs) formed and strengthened**
 If a member is removed from CPC group, It is not reflecting in the report.
for eg: removed a member from CPC Group 2 but number of male is same as before.
- Same is true for Adolescent group also.
- Indicator - **"Number of campaign / events on girls’safety organized"**
space between girls'safety.
- Indicator - **"Number of Workshops on Family Resilience Planning conducted"**, numbers from event reporting is not taking,
- Also, for the same indicator, male and female count is not right. total female in one meeting are 11 and male are 4. (assuming in female we are counting both women and girls)
**Eg:** - _Events_, in this subject, type is selected "disaster and resilience" is selected but not reflecting in report.
- Indicator - **"Number of awareness/orientation sessions on SS schemes"**, check for the same issue as above indicator.
-Indicator - **"Number of vulnerable and at-risk children identified"**, number is showing 25 but there are not 25 children that were enrolled in any vulnerability.
- Indicator - "Number of orientation / training sessions for Child Champions", sum is not right. not taking value from Other Stakeholders Training. Subject - Other

**Comment by garimadosar5** [comment]
**QA Notes 2 -** 
- Indicator - **"Number of Workshops on Family Resilience Planning conducted"**, numbers from event reporting is not taking,
- Also, for the same indicator, male and female count is not right. total female in one meeting are 11 and male are 4. (assuming in female we are counting both women and girls)
**Eg:** - _Events_, in this subject, type is selected "disaster and resilience" is selected but not reflecting in report.
In this indicator, Male/female number is not increasing from 1. I filled some data in CPC1 group.
- In all the indicators, boys and girls are not included in Male/female numbers.
- Indicator - "Number of awareness/orientation sessions on SS schemes", check for the same issue as above indicator. **Please share any encounter /subject having data for this indicator**
- Indicator - **"Number of orientation / training sessions for Child Champions"**, sum is not right. not taking value from Other Stakeholders Training. Subject - Stakeholder **Fixed**
