### ISSUE TITLE
[STCATP][Report] MIS Report - ER2

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#31]
https://docs.google.com/spreadsheets/d/1AvBcssHonsota3UcYEWpOw2kILisAQaq/edit#gid=227783172

**Comment by nupoorkhandelwal** [comment]
Moving to on Hold as logic of following indicators are not yet clear -
1.
https://docs.google.com/spreadsheets/d/1AvBcssHonsota3UcYEWpOw2kILisAQaq/edit#gid=227783172&range=A42:A43

2.https://docs.google.com/spreadsheets/d/1AvBcssHonsota3UcYEWpOw2kILisAQaq/edit#gid=227783172&range=A52

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Indicator "Number of orientation / training sessions on the CRBP and sustainable business practices for STGs and FPOs conducted"
Male/female should count the number from question "total no of men present (not part of the group)". Please check once.
-  **Fixed**
