### ISSUE TITLE
[STCATP][Form] Monthly Planner

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#33]
## Context
There will be monthly plans submitted by Community Mobiliser, District Officer and Program Manager. 
The monthly plans submitted by the Community Mobiliser should be approved by District Officer.
These monthly plans will be used to track the progress against targets in the Project MIS report. The numbers entered in this form will become target.

## Acceptance Criteria
1. As a community mobiliser i should see a form to be filled to submit monthly plan. All the fields should be mandatory.
2. As a district officer i should see a form to be filled to submit monthly plan. All the fields should be mandatory.
3. As a district officer i should get monthly plans submitted by community mobilesers from my district for approval. I should be able to approve or reject with corrections
4. As a community mobiliser and district officer i should see cards in dashboard for approval, rejection, etc. 

## Tech
1. Create a subject type called : Monthly Planner of type Individual
2. Create a general encounter 'Monthly Plan'
3. The set of fields are different for community mobiliser and district officer. They are marked in the sheet here : https://docs.google.com/spreadsheets/d/1AvBcssHonsota3UcYEWpOw2kILisAQaq/edit#gid=227783172

**Comment by garimadosar5** [comment]
**QA Notes-** 
- Sums in forms are not correct.
![Screenshot_2021-09-01-17-56-01-69_e67de974eab1ae435bf1faa372eb4549.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/4c65ee7a-c697-4859-a411-ae34c8f1ff12)
