### ISSUE TITLE
Parenting without Violence Report

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#39]
https://docs.google.com/spreadsheets/d/1QEM93Kxw4bBKQO0fh0wXy4nNUWCC0rSQ/edit#gid=1550032078

Refer Sheet 2

**Comment by sachsk** [comment]
Report link :-  https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2FSave_the_Children_Assam_Tea_Plantation%2FReports%2FAggregates&reportUnit=%2FSave_the_Children_Assam_Tea_Plantation%2FReports%2FAggregates%2FParenting_without_violence&standAlone=true

**Comment by garimadosar5** [comment]
QA Notes - 
- Put NA where % is not being calculated.
- Indicator - "Adolescent group members (boys/girls) participated in PwV sessions", here child champions will be calculated or not as child champions are calculated in next indicator.

**Comment by sachsk** [comment]
In "Adolescent group members (boys/girls) participated in PwV sessions" we have counted all attendees
