### ISSUE TITLE
Vulnerable Child Case Tracking 

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#4]
## Context
Vulnerable children are identified from various sources and followed through and removed from vulnerability. There can exist multiple types of vulnerability.

## Solution
For each type of vulnerability user will enrol into a different program. In the Enrolment form, identification and reporting details will be filled

## Acceptance Criteria
1. I should be able to Enrol into following programs : Child Labour | Out of school | Child Abuse | Child Marriage | Missing Child | Trafficked Child | Orphan / Single Parent
2. Enrolment form will be different for each type of vulnerability.
3. Enrolment First page will be Identification details
4. Enrolment Second page will be Reporting details
5. I should be able to fill Status follow up form every month until i close the case. It should be scheduled
6. I should be able to exit when the case is closed.

Reference Document : https://docs.google.com/spreadsheets/d/1NKq9g6DE6IxMcKIbnTNMkFpSm5BZC3l6/edit#gid=3235262

| Vulnerability (Program)        | Forms           | 
| ------------- |:-------------:| 
| Child labour      | Enrolment (once), Status Follow up (monthly), Exit (once) | 
| Out of school      | Enrolment (once), Status Follow up (weekly for first 2 months, then monthly), Mainstream follow up (quarterly), Exit (once) |   
| Child abuse | Enrolment (once), Status Follow up (weekly for first 2 months, then monthly), Exit (once)      |
| Child marriage | Enrolment (once), Status Follow up (weekly for first 2 months, then monthly), Exit (once)      |
| Missing child  | Enrolment (once), Status Follow up (weekly for first 2 months, then monthly), Exit (once)      |
| Trafficked child | Enrolment (once), Status Follow up (weekly for first 2 months, then monthly), Exit (once)      |
| Orphan / single parent | Enrolment (once), Status Follow up (weekly for first 2 months, then monthly), Exit (once)      |

**Enrolment Form**
**Identification** 
- Type of child labour | Type of child abuse
- Case identified by
- Case identification date

**Reporting**
- Child abuse case reported to CWC/Police | Child marriage case reported to concerned authority | ..
- Case reported by
- Case reporting date

- [x] Child labour

- [x] Out of school 

- [x] Child abuse

- [x] Child marriage 

- [x] Missing child  

- [x] Trafficked child

- [x] Orphan / single parent

**Comment by garimadosar5** [comment]
**QA Notes -** 
- On edit, a new visit gets generated.
- Child Abuse - status follow-up form, Save button is not working. (form is stuck on the last page).
- Child Marriage - FE - "Child marriage reported by". Make NONE unique option.
- In different programs. scheduling is different for Case planning, case assessment.
For child abuse, it is diff from other modules.
