### ISSUE TITLE
[STCATP] Feedback from demo call

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/stcatp#41]
- [x] Duration of training - inclusive

- [x] Auto calculate Total direct reach, Total indirect reach

- [x] Add Validation - total score count should not be greater than total of Attendance

- [x] Update group roles for Adolescent group 

- [x]  Other Stakeholder training attendee Registration - make mobile number & email id non mandatory

**Comment by garimadosar5** [comment]
**QA Notes -** 
- In training Duration of training is by default 1. even when there is no date filled. It should be 0 then.
