### ISSUE TITLE
Reports UAT Feedback

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#43]
Line Items in this sheet from 'Feedback on Report Template' line onwards
https://docs.google.com/spreadsheets/d/15tkKxrYEikk9robsiiWqQ11P1MVRzc3iGDeJIgo4F60/edit#gid=0

Make all the reports consistent.
- Do not show 'null' anywhere
- Do not show empty cells. It should either be 0 or NA. 
- header should be there in all tables
- header colour should be same in all tables / reports

**Comment by nupoorkhandelwal** [comment]
QA notes -
1. Outcome report 1 - Percentage column is blank after applying 1st nov 2021 -15th nov 2021
2. Where are CPC related linelists used. we should delete them if not used 
3. Outcome report 1 > Column name Target is all caps. Make it camelCase.
