### ISSUE TITLE
[STCATP] Report changes post training app changes

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/stcatp#48]
- [x] Fix reports wherever event reporting subject types is used to fetch numbers.

- [x] Add Date filter on reach report

- [x] Report: ER1 two indicators are showing wrong - 
Number of Child champions identified for child led advocacy - this is actually 0
Family resilience planning conducted - Fixed

**Comment by garimadosar5** [comment]
**QA Notes -** 
- ER1 report - indicators "Number of Child Champions identified for Child led Advocacy" Total is 69 but Male-female separately is showing 0 (In Targeted).

Because we dont capture it. Have made it NA as the value now.
