### ISSUE TITLE
[STCATP Support] Add shared schemes and their status

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/stcatp#49]
https://avni.freshdesk.com/a/tickets/2313
 
Add following to the "Schemes" coded concept in "SS facilitation" form - 
1. Assam Orunodoi
2. Ayushman Bharat
3. Provident and Fund scheme
4. Others

Add following to the "Schemes status" field in "SS Facilitation status update" form as already done for other schemes-
1. Assam Orunodoi
2. Ayushman Bharat
3. Provident and Fund scheme
4. Others

**Comment by vedfordev** [comment]
Test this one on client.

**Comment by AchalaBelokar** [comment]
- [x] Others their must be specify other question require
