### ISSUE TITLE
STCATP small Tickets

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#50]
- [x] https://avni.freshdesk.com/a/tickets/2600
- [x] https://avni.freshdesk.com/a/tickets/2599
 Done on UAT, changed the program enrolment age limit to 24 instead of 18.
- [x] https://avni.freshdesk.com/a/tickets/2597
- [x] https://avni.freshdesk.com/a/tickets/2596
- [x] https://avni.freshdesk.com/a/tickets/2593
- [x] https://avni.freshdesk.com/a/tickets/2591

**Comment by AchalaBelokar** [comment]
- [ ] https://avni.freshdesk.com/a/tickets/2598 - Change is still not clear 
still 

- [ ] what is the difference between Ayushman Bharat , Ayushman Bharat Yojana..
- [ ] According to the card status should be update but it is not working..

**Comment by AchalaBelokar** [comment]
[https://app.zenhub.com/files/388093895/c243cebe-85fc-4325-863a-0bd727e89f47/download](https://app.zenhub.com/files/388093895/c243cebe-85fc-4325-863a-0bd727e89f47/download)
