### ISSUE TITLE
CPC Group Meeting

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#9]
Reference : https://docs.google.com/spreadsheets/d/1eeBtAKH93hdJODWrm_xuNhbFm0H6vDKk/edit#gid=1702887214

This will be a encounter type on Group 'CPC Group'

**Key fields in the encounter**
- Facilitator
- Purpose of the meeting
- Agenda developed
- Action plan developed
- Attendance [All the members of the group should show up]
- Responsible to implement the action plan [All members of the group should show up]
- Meeting minutes available: Yes / No
- Upload meeting minutes [Image type]

**Comment by garimadosar5** [comment]
Next meeting date is missing here but I have added as It was there in the sheet,
@arjunk
